Task_02
Glebuska/python_basic_programming pull request #1
Opened 2020-03-09 13:28 UTC by Glebuska

2020-03-10 12:58 UTC, SpirinEgor requested changes
Очень много ненужных файлов, по некоторым отписал.
Так же не очень понятно, зачем тебе тут `sqlite` файл
+ серверная часть ничего не знает о `js` и `html`, так что они не должны появляться в папке `server`, с ними ты работаешь на клиенте

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/Untitled.ipynb
> +{
Выглядит, как тестовый файл, в котором ты изучал возможности либы, не думаю, что он должен быть в репозитории.
Если же хочешь оставить его, то назови нормально файл, а ещё лучше очистить вывод ячеек, сбросить счётчик исполнений и добавить какое-нибудь описание.

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/client/debug.log
> +[0307/115459.912:ERROR:crash_report_database_win.cc(428)] unexpected header
Логи точно не индексируют в гите

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/client/index.html
> +{"shortName":"Джинсы "Flex Slim"","brandName":"skills ","price":4122}
Зачем это тут?

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/debug.log
> +[0304/154103.548:ERROR:crash_report_database_win.cc(428)] unexpected header
Опять логи

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/server/app_db.py
>              """CREATE TABLE IF NOT EXISTS Users
Таблица сейчас, наверное, по-другому называется

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +            db_conn.execute(query)
Это можно сделать за один `insert`, там можно данные для вставки через запятую указывать

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +def parse_site(ref):
Если у тебя всё-таки ограниченый пул сайтов, то лучше сделать такую функцию для каждого сайте по отдельности.

Сейчас получается довольно странно, ты сначала выбираешь сайт и ссылку к нему, передаёшь только ссылку в функцию, а внутри обратно сайт достаёшь и делаешь парсинг взависимости от этого

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        data = [item['data-params'] for item in soup.find_all('div', attrs={'data-params': True})]
Вот это первая функция: `parse_citilink`

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +            data.append(json_model)
Вот это `parse_wildberries`

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +                                                         "") + '","brandName":"' + brandName.replace("'", "") + '","price":' + price + "}"
В python есть f-строки, можно писать
`{"shortName" : "{name.replace()}", ...`
Будет аккуратно, без всей конкатенации

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        ref_of_site = "https://www.wildberries.ru/catalog/0/search.aspx?search=%D0%BC%D1%83%D0%B6%D1%81%D0%BA%D0%B8%D0%B5%20%D1%87%D0%B5%D1%80%D0%BD%D1%8B%D0%B5%20%D0%B4%D0%B6%D0%B8%D0%BD%D1%81%D1%8B
Будет либо, `parse_citilink()`, либо `parse_wildberries()`

2020-03-10 12:58 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    return render_template("index.html")
Всё-таки лучше разделять фронт и бек и не передавать html с сервера, не надо использовать темплейты

2020-03-10 14:29 UTC, Glebuska commented on assignment_2/server/app_db.py
> +def parse_site(ref):
Не совсем понятно, как пишут на практике. А допустим у нас есть 10 сайтов, разве заводить 10 разных функций, где меняется один параметр, норм идея?

2020-03-10 14:36 UTC, Glebuska commented on assignment_2/server/app_db.py
> +    return render_template("index.html")
Тогда все такие скрипты лучше через js писать, так? 
Запускать html файл, допустим home_page, кидать в него ссылку, которая обрабатывается через js, и с помощью того же js, подключать html для новой ссылки на сайте ("\get_all")
Алгоритм верен?

2020-03-15 11:37 UTC, SpirinEgor requested changes
1. Давай вернём `app_base`, пусть он будет без изменений, чтобы пр его просто не индексировал (этот файл не имеет никакого отношения к проделанной работе, поэтому странно его тут видеть).
2. Не много не понял клиентскую часть:
a. Основной файл можно назвать `index.html`, тогда это будет стартовый файл сайта, не надо будет переходить по url, но это как хочешь сам.
b. При загрузке страницы вызывается функция `draw_table`, которая делает запрос на `/get_all`, но таблица может быть пустой ещё. Весь парсинг происходит при запросе на `/`, но с клиента такой запрос никогда не поступает. Может тебе сделать 2 кнопки, каждая из которых делает запрос на сервер для парсинга соответствующего сайта, если его информации ещё нет в бд?

2020-03-15 11:37 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +from flask import Flask, g, request, url_for, redirect, flash, render_template, render_template_string
Половина импортов не используется, их можно удалить

2020-03-15 11:37 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +pattern = "\www.(.*?)\."
Для обозначения регулярных выражений используются r-строки
```
r'<pattern>'
```
И я не вижу использования этого паттерна

2020-03-15 11:37 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    data = list()
Лист можно инициализировать `[]`

2020-03-15 11:37 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    prices = list(map(lambda x: re.sub("\D", "", x.string), soup.find_all("ins", class_='lower-price')))
Так как дальше ты работаешь c `zip` от этих объектов, то не надо кастовать к листьям, оставь генераторы.

Так же, у тебя везде используются `"` и `'` для обозначения строк. Для питона без разницы, как ты это делаешь, поэтому есть просто договорённости, что `"` -- строки, которые видит пользователь (ты их печатаешь или ещё как-то отображаешь), а для `'` -- что-то локальное. Мне без разницы, но хочется чтобы было единообразно.

2020-03-15 11:37 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    for name, brandName, price in zip(names, brand_names, prices):
в питоне используют `snake_case` для названия переменных

2020-03-15 11:37 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        json_model = "{" + f'"shortName":"{name}","brandName": "{brandName}", "price":{price}' + "}"
Это можно сделать одной f-строкой

2020-03-15 11:37 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        json_model = "{" + f'"shortName":"{name}","brandName": "{brandName}", "price":{price}' + "}"
Ну и про пробелы внутри строки не забывай, а то строка криво выглядит

2020-03-15 11:37 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    create_new_item(data, "Wildberries")
Опять же, тут `"Wildberries"`, а выше `'Citilink'`. Хочется одинаково :smile:

2020-03-16 17:48 UTC, SpirinEgor requested changes
По коду замечаний нет, непонятно как пользоваться.
Я запустил и получил пустую страницу, непонятно как наполнить таблицу контентом. Надо либо при запуске страницы делать запрос на сервер, либо кнопочку прикрутить.

2020-03-19 10:33 UTC, SpirinEgor approved these changes

2020-03-19 18:50 UTC, merged