Task_03
Glebuska/python_basic_programming pull request #5
Opened 2020-04-20 06:07 UTC by Glebuska

2020-04-20 08:19 UTC, Glebuska commented on task_03/app.py
> +                flash("No face detection. Please upload image with face")
Непонятно почему, но этот flash не хочет отображаться.
Чтобы как-то сказать пользователю, что он не то изображение отправляет, пытался делать так: `return redirect(/error_handle)` , но он не хочет переходить почему-то -_-

2020-04-20 11:11 UTC, SpirinEgor requested changes

2020-04-20 11:11 UTC, SpirinEgor commented on task_03/app.py
> +from flask_uploads import UploadSet, configure_uploads, IMAGES, patch_request_class
Этот пакет не работает с werkzeug>=1.0, на pypi последнее обновление за 2016 год. Лучше от него отказаться в пользу более современного и безопасного.

2020-04-20 11:11 UTC, SpirinEgor commented on task_03/logic.py
> +def readPoints(points):
Хоть код и копировался, неплохо было бы поддержать styleguide во всём файле

2020-04-20 11:11 UTC, SpirinEgor commented on task_03/logic.py
> +    return True
Можно сделать более аккуратно, не плодить каскад условий

2020-04-20 11:11 UTC, SpirinEgor commented on task_03/logic.py
> +        pt3 = (t[4], t[5])
Тоже выглядит странно, можно нормально развернуть `t` в точки, потом их же использовать, чтобы добавить в `pt`, например, `pt += [pt1, pt2, pt3]`

2020-04-20 11:11 UTC, SpirinEgor commented on task_03/app.py
> +                flash("No face detection. Please upload image with face")
Всплывающие окна могут быть заблокированны браузером. Можно без редиректа, добавь в `index.html` поле для ошибки, а тут отрендерь его с этой ошибкой

2020-04-27 09:20 UTC, SpirinEgor requested changes

2020-04-27 09:20 UTC, SpirinEgor commented on task_03/app.py
> +    first_img = file_names[len(file_names) - 3]
Запускаю, в оба окошка вставляю по картинке, нажимаю кнопку и всё падает на этой строчке с ошибкой `list index out of range`

2020-04-27 09:20 UTC, SpirinEgor commented on task_03/app.py
> +        if len(file_names) % 2 == 0:
Не очень понял эту проверку, вроде как достаточно проверить, что длина больше или равна 2

2020-04-27 09:20 UTC, SpirinEgor commented on task_03/app.py
> +                second_img = file_names[len(file_names) - 1]
Можно `[-2]` и `[-1]`

2020-04-27 09:56 UTC, SpirinEgor requested changes

2020-04-27 09:56 UTC, SpirinEgor commented on task_03/logic.py
> +    return True
```
if <expr>:
    return False
return True
```
Не надо так делать...
```
return not <expr>
```

2020-04-29 16:37 UTC, SpirinEgor approved these changes

2020-04-30 17:47 UTC, merged